### ISSUE TITLE
what's the dataset?

### ISSUE THREAD

**Issue by SeekPoint** [jimcaine/rtb#1]
CHARTS_DIR_PATH = './charts/'
TABLES_DIR_PATH = './tables/'
DATA_PATH = './data/'
IMP_TRAIN_PATH = './raw_data/imp_train.txt'
CLICK_TRAIN_PATH = './raw_data/click_train.txt'
IMP_TEST_PATH = './raw_data/imp_test.txt'
CLICK_TEST_PATH = './raw_data/click_test.txt'

**Comment by jimcaine** [comment]
The raw dataset is from an RTB dataset released by a company called iPinYou: http://data.computational-advertising.org/

**Comment by SeekPoint** [comment]
it looks that the file like 
imp_train.txt  click_train.txt 
are the pre-process results from ipinyou dataset

would you please provide how you generates those files, thanks

**Comment by SeekPoint** [comment]
hello

**Comment by leopeng1995** [comment]
@loveJasmine See Section 2 of the paper.
