### ISSUE TITLE
Dataset!

### ISSUE THREAD

**Issue by saeidsoheily** [jimcaine/rtb#2]
I could not find the dataset which you mentioned.
I downloaded the dataset from RTB data by iPinYou, but there is no files such as:
train_imp_fs.csv
train_sample_%s.csv
impression_sample.txt
,...

Please let me know how can I run your code with a correct dataset.
Thanks

**Comment by jimcaine-eyeview** [comment]
Hi @saeidsoheily ,

The files that you mentioned are just preprocessed datasets from the original iPinYou dataset.  For example, train_imp_fs.csv is generated using the function "feature_selection_imps()".  impression_sample.txt is just the impressions table but sampled for quicker processing.  train_sample_%s.csv are random stratified samples of the dataset, where %s represents the majority to minority sampling ratio.

Looking back into the code, I am realizing that it is quite messy (was still a bit of a python novice at the time) and really wasn't intended for open source use.  I would highly recommend just getting the basic ideas from the paper (ie the simulation to check for pacing, etc) and re-writing the code.

Hope that helps,
Jim.
